# dockerfile.tests

FROM python:3.12-slim-bookworm

ARG USER_ID=1001
ARG GROUP_ID=1001

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    default-libmysqlclient-dev \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip --root-user-action=ignore && \
    pip install --no-cache-dir -r requirements.txt --root-user-action=ignore && \
    groupadd --gid ${GROUP_ID} testuser && \
    useradd --uid ${USER_ID} --gid ${GROUP_ID} --create-home --shell /bin/bash testuser

COPY ./printqa ./printqa
COPY ./tests ./tests
COPY ./scripts ./scripts
COPY ./app ./app
COPY pytest.ini .
COPY conftest.py .
COPY ./alembic.ini .
COPY ./alembic ./alembic

RUN mkdir -p /app/reports && \
    chmod 755 /app/reports

RUN chmod +x ./app/*.sh
RUN chown -R testuser:testuser /app

USER testuser

ENTRYPOINT ["./app/run_local_tests.sh"]
