# docker-compose.yml

services:
  db:
    image: mariadb:10.6
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build: . 
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      DATABASE_URL: mysql+mysqlconnector://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

  tests:
    build:
      context: .
      dockerfile: dockerfile.tests 
    env_file:
      - ./.env
    environment:
      
      DATABASE_URL: mysql+mysqlconnector://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      
      TESTRAIL_HOST: ${TESTRAIL_URL}
      TESTRAIL_USERNAME: ${TESTRAIL_USER}
      TESTRAIL_PASSWORD: ${TESTRAIL_KEY}
      TESTRAIL_PROJECT_ID: ${TESTRAIL_PROJECT_ID}
      TESTRAIL_SUITE_ID: ${TESTRAIL_SUITE_ID}
      TESTRAIL_RUN_ID: ${TESTRAIL_RUN_ID}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./reports:/app/reports  
    command: ["./run_local_tests.sh"]

volumes:
  db_data: