# dockerfile.tests

FROM python:3.12-slim-bookworm

WORKDIR /app

# --- Instalação de Dependências de Sistema ---
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    default-libmysqlclient-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# --- Instalação de Dependências Python ---
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# --- Cópia do Código da Aplicação e Testes ---
COPY ./printqa ./printqa
COPY ./tests ./tests
COPY ./scripts ./scripts
COPY ./app ./app
COPY pytest.ini .
COPY conftest.py .

RUN mkdir -p /app/reports

ENTRYPOINT ["./app/run_local_tests.sh"]