# .github/workflows/ci.yml
name: PrintQA CI/CD Pipeline

on:
  push:
    branches: [ main, develop, qa ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test-and-analyze:
    name: Testes e Análise de Qualidade
    runs-on: ubuntu-latest
    
    # --- Adiciona banco de dados (MySQL MariaDB) ---
    services:
      mysql:
        image: mysql:8.0 
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: test_printqa_db
        ports:
          - 3306:3306 
        options: >- 
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_URL }}
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USER }}
      TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_KEY }} 

      DB_USER: ${{ secrets.DB_USER }} 
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }} 
      DB_HOST: mysql 
      DB_PORT: 3306 
      DB_NAME: test_printqa_db 
      DATABASE_URL: "mysql+mysqlconnector://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}"

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Dependências (incluindo DB e CLI)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      # --- PASSO 1: Rodar Testes Pytest e Gerar Relatório JUnit XML ---
      - name: Rodar Testes e Gerar Relatório JUnit
        run: |
          # DATABASE_URL já está disponível no ambiente devido ao 'env:' do job
          pytest --cov=printqa --junitxml="junit-report.xml" "./tests" 

      # --- PASSO 2: Enviar Resultados para TestRail usando TestRail CLI (trcli) ---
      - name: Enviar Resultados para TestRail via CLI
        run: |
          trcli -y \
            -h "${{ env.TESTRAIL_HOST }}" \
            --project "PrintQA" \
            --username "${{ env.TESTRAIL_USERNAME }}" \
            --password "${{ env.TESTRAIL_PASSWORD }}" \
            parse_junit --title "Pytest Run - ${{ github.run_id }}" \
            -f junit-report.xml