# .github/workflows/ci.yml
name: PrintQA CI/CD Pipeline

on:
  push:
    branches: [ main, develop, qa ]
  pull_request:
    branches: [ develop, main ]

jobs:
  # Job para Testes de Unidade/Integração do Backend e Análise de Qualidade
  test-and-analyze:
    name: Testes e Análise de Qualidade (Backend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Create .env file for tests
        run: |
          cat > .env << EOF
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          TEST_DB_NAME=${{ secrets.TEST_DB_NAME }}
          TESTRAIL_URL=${{ secrets.TESTRAIL_URL }}
          TESTRAIL_USER=${{ secrets.TESTRAIL_USER }}
          TESTRAIL_KEY=${{ secrets.TESTRAIL_KEY }}
          TESTRAIL_PROJECT_ID=${{ secrets.TESTRAIL_PROJECT_ID }}
          TESTRAIL_SUITE_ID=${{ secrets.TESTRAIL_SUITE_ID }}
          TESTRAIL_RUN_ID=${{ secrets.TESTRAIL_RUN_ID }}
          TESTRAIL_DRY_RUN=${{ secrets.TESTRAIL_DRY_RUN }}
          USER_ID=1001
          GROUP_ID=1001
          EOF

      - name: Create reports directory with proper permissions
        run: |
          mkdir -p reports
          chmod 777 reports

      - name: Build and Run Docker Compose Tests
        # Este comando irá construir automaticamente todas as imagens (api, frontend, tests)
        # e serviços de banco de dados que o serviço 'tests' depende,
        # e então executará os testes de backend.
        run: |
          docker compose up --build --abort-on-container-exit --exit-code-from tests

      - name: Fix reports permissions (if needed)
        if: always()
        run: |
          sudo chown -R runner:docker reports/ 2>/dev/null || true
          chmod -R 644 reports/*.xml 2>/dev/null || true

      - name: Upload Relatório de Testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-reports
          path: reports/junit-report.xml
          retention-days: 7

      - name: Debug - List reports directory
        if: always()
        run: |
          echo "Contents of reports directory:"
          ls -la reports/ || echo "Reports directory not found"

  