# .github/workflows/ci.yml
name: PrintQA CI/CD Pipeline

on:
  push:
    branches: [ main, develop, qa ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test-and-analyze:
    name: Testes e Análise de Qualidade
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Build and Run Docker Compose Tests
        run: |
          docker-compose up --build --abort-on-container-exit --exit-code-from tests
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: test_printqa_db
          TESTRAIL_URL: ${{ secrets.TESTRAIL_URL }}
          TESTRAIL_USER: ${{ secrets.TESTRAIL_USER }}
          TESTRAIL_KEY: ${{ secrets.TESTRAIL_KEY }}

      - name: Upload Relatório de Testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-reports
          path: reports/junit-report.xml
          retention-days: 7